name: Login
oauth2:
  GitHub:
    clientID: your-client-id
    clientSecret: your-client-secret
    clientIDParamName: client_id
    clientSecretParamName: client_secret
    redirectUri: http://localhost:8080/login/callback
    redirectUriParamName: redirect_uri
    accessTokenUri: https://github.com/login/oauth/access_token
    authorizationUri: https://github.com/login/oauth/authorize
    userdataUri: https://api.github.com/user

loginform:
  name: loginform
  title: Login
  sections:
    simple:
      label: Fake Login
      fields:
        - name: username
          type: text
          label: Username
        - name: password
          type: password
          label: Password
        - name: rememberMe
          type: checkbox
          value: store
          text: Remember Login
        - type: submit
          name: submit
          label: Click to Submit
          value: submit login
