# To execute this docker-compose yml file use docker-compose -f <file_name> up
# Add the "-d" flag at the end for deattached execution
version: "3.5"

services:
  boilerplate-server:
    build:
      context: .
    image: uwegerdes/expressjs-boilerplate
    container_name: boilerplate-server
    hostname: boilerplate-e2e
    ports:
      - 51285:8080
      - 51286:8081
    environment:
      NODE_ENV: development
      LIVERELOAD_PORT: 51286
    volumes:
      - .:/home/node/app
    command: npm run dev

  boilerplate-e2e-hub:
    image: selenium/hub
    container_name: boilerplate-e2e-hub
    hostname: boilerplate-e2e-hub
    ports:
      - 54442:4442
      - 54443:4443
      - 54444:4444

  boilerplate-e2e-chrome:
    image: selenium/node-chrome
    container_name: boilerplate-e2e-chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - boilerplate-e2e-hub
    environment:
      SE_EVENT_BUS_HOST: boilerplate-e2e-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      JAVA_OPTS: -Dselenium.LOGGER.level=WARNING

  boilerplate-e2e-firefox:
    image: selenium/node-firefox
    container_name: boilerplate-e2e-firefox
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - boilerplate-e2e-hub
    environment:
      SE_EVENT_BUS_HOST: boilerplate-e2e-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      JAVA_OPTS: -Dselenium.LOGGER.level=WARNING

  boilerplate-e2e-frontend:
    image: uwegerdes/e2e-workflow
    container_name: boilerplate-e2e-frontend
    hostname: boilerplate-e2e-frontend
    ports:
      - 51287:8080
      - 51288:8081
    depends_on:
      - boilerplate-e2e-hub
    environment:
      HUB_HOST: boilerplate-e2e-hub
      HUB_PORT: 4444
      NODE_ENV: staging
      LIVERELOAD_PORT: 51288
    volumes:
      - ./modules:/home/node/app/config/modules
      - ./results:/home/node/app/results
      # for e2e development
      - ../docker-e2e-workflow/modules/e2e:/home/node/app/modules/e2e
      - ../docker-e2e-workflow/fixture:/home/node/app/fixture
    command: npm run dev
